### PR TITLE
Lambda

### PR DESCRIPTION
**Pull request by zmj**
fyi @qguv - testing / fixes welcome on the batch stuff. Don't think this should have broken it but not sure how to verify

### CODE REVIEW

**Comment by qguv** [comment]
Hey @zmj,

Previously I could run `go build` which would produce a binary `mtg-aggregatedeck` in the root directory of this project. I can't do that anymore, and if I try to run `go get` in the cli directory, go complains:

    batch.go:10:2: use of internal package not allowed

Now that your deployment looks different (lambda), how are you compiling this locally to test?

Should you want to test batch mode yourself: batch mode was built to accompany [my friend's deck scraper tool](https://bitbucket.org/bjones5001/mtgscraper) so that decks could be scraped and aggregated automatically. That tool right now spits output into `~/Documents/decks`; you can use that as input to the batch mode to test it.

**Comment by zmj** [comment]
@qguv odd that CLI isn't building for you - I can go build / install in that directory fine. Do you have the folder structure as it exists in the current repo? CLI has to be a sibling folder of internal to reference it.

**Comment by qguv** [comment]
Yes, I have the latest version of the repo and am on the `master` branch. [Here's a terminal session](https://ptpb.pw/VuUI) of me trying to get it built.

**Comment by zmj** [comment]
Looks like your GOPATH isn't set? Or is set somewhere other than the directory you checked out this repo? On 1.8 and above, default GOPATH is $HOME/go and <1.8 you have to set it explicitly.

The result is that the go tool doesn't realize that batch.go should have access to the internal/logic package. It's looking for that package in your GOPATH.

Here's the documentation on how to set up a Go workspace: https://golang.org/doc/code.html#Workspaces 

For example, my environment is:
zmbp:cli zmj$ echo $GOPATH
/Users/zmj/golang
zmbp:cli zmj$ pwd
/Users/zmj/golang/src/github.com/zmj/mtg-aggregatedeck/cli

**Pull request merged**
